default: &default
  adapter: postgresql
  encoding: unicode
  #раскомментировать при деплое:
  #host: localhost

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dack_site_development

test:
  <<: *default
  database: dack_site_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :database) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :user) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :password) %>
