Type.create!(photo_type: 'Макро')
Type.create!(photo_type: 'Пейзажи')
Type.create!(photo_type: 'Портреты')
Type.create!(photo_type: 'С квадрокоптера')
Type.create!(photo_type: 'Коллажи')
Type.create!(photo_type: 'Остальное')
